// AUTO-GENERATED by scripts/process-backgrounds.mjs — do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

export interface ImageAsset { id: string; source: ImageSourcePropType; fallbackColor: string }

export const IMAGE_ASSETS: readonly ImageAsset[] = [
  { id: 'scene-01', source: require('../../../assets/backgrounds/scene-01.webp'), fallbackColor: '#181818' },
  { id: 'scene-02', source: require('../../../assets/backgrounds/scene-02.webp'), fallbackColor: '#382818' },
  { id: 'scene-03', source: require('../../../assets/backgrounds/scene-03.webp'), fallbackColor: '#283828' },
  { id: 'scene-04', source: require('../../../assets/backgrounds/scene-04.webp'), fallbackColor: '#88c8d8' },
  { id: 'scene-05', source: require('../../../assets/backgrounds/scene-05.webp'), fallbackColor: '#487898' },
  { id: 'scene-06', source: require('../../../assets/backgrounds/scene-06.webp'), fallbackColor: '#080808' },
  { id: 'scene-07', source: require('../../../assets/backgrounds/scene-07.webp'), fallbackColor: '#483818' },
  { id: 'scene-08', source: require('../../../assets/backgrounds/scene-08.webp'), fallbackColor: '#c8c8d8' },
  { id: 'scene-09', source: require('../../../assets/backgrounds/scene-09.webp'), fallbackColor: '#282828' },
  { id: 'scene-10', source: require('../../../assets/backgrounds/scene-10.webp'), fallbackColor: '#787878' },
  { id: 'scene-11', source: require('../../../assets/backgrounds/scene-11.webp'), fallbackColor: '#383818' },
  { id: 'scene-12', source: require('../../../assets/backgrounds/scene-12.webp'), fallbackColor: '#180808' },
  { id: 'scene-13', source: require('../../../assets/backgrounds/scene-13.webp'), fallbackColor: '#8898a8' },
  { id: 'scene-14', source: require('../../../assets/backgrounds/scene-14.webp'), fallbackColor: '#181818' },
  { id: 'scene-15', source: require('../../../assets/backgrounds/scene-15.webp'), fallbackColor: '#f8d8a8' },
  { id: 'scene-16', source: require('../../../assets/backgrounds/scene-16.webp'), fallbackColor: '#281818' },
  { id: 'scene-17', source: require('../../../assets/backgrounds/scene-17.webp'), fallbackColor: '#685848' },
  { id: 'scene-18', source: require('../../../assets/backgrounds/scene-18.webp'), fallbackColor: '#280808' },
  { id: 'scene-19', source: require('../../../assets/backgrounds/scene-19.webp'), fallbackColor: '#582808' },
  { id: 'scene-20', source: require('../../../assets/backgrounds/scene-20.webp'), fallbackColor: '#e8b858' },
];
